
name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      # - name: Get dependencies
      #   run: 'yarn'
      # - name: Build output
      #   run: 'yarn build'
      - uses: ./
        with:
          name: deploy-worker-action
          main: "./worker.js"
          domain: template.do
          cloudflareApiToken: ${{ secrets.CF_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CF_ACCOUNT_ID }}
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "🚀 Built Successfully"
      #     push_options: --force
